# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('published_date',)},
        ),
    ]
