# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20160529_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=128),
        ),
    ]
